services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: sh -c "python answer_questions.py && python app.py"